### PR TITLE
Ubuntu18.04 configuration

### PR DESCRIPTION
**Pull request by DonnieKim411**
To make Ubuntu18.04 compatible, I added some lines that install `wxPython`, `libgtk-3-0`, and  `python3-tk`.

Just to note, it know `wxPython` is installed from `ubuntu-16-04`, but it still worked fine...

Also, in `dlc-docker`, i added lines that also give `DISPLAY` values so that ppl can plot things in jupyter.

### CODE REVIEW

**Comment by DonnieKim411** [comment]
Also, have you guys thought directly adding `dlc-docker` and `Dockerfile` in https://github.com/AlexEMG/DeepLabCut ? I think it is confusing how docker settings are in a separate repo... i feel that this repo should be a subset of `DeepLabCut`

**Comment by MMathisLab** [comment]
can you launch the GUIs? and/or why do you want GUI support inside the container?

**Comment by MMathisLab** [comment]
I tested your commits; there was an error in DISPLAY that I fixed. Now when I launch the container, with the additional display call, via:

``GPU=1 bash ./dlc-docker run -d -p 2353:8888 -e USER_HOME=$HOME/DEEPLABCUT -e DISPLAY=$DISPLAY --name wxdlctesting dlc_wxtesting/dlcdocker``

indeed ``import deeplabcut`` runs without errors even without setting DLClight=True. However, when testing in the Jupyter notebook (reaching-example) I get the following error when I run ``dlc.check_labels()`` it creates the folder, but does not create the images and I get the following error:

```
/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py in new_figure_manager_given_figure(cls, num, figure)
   1042         """
   1043         _focus = windowing.FocusManager()
-> 1044         window = Tk.Tk(className="matplotlib")
   1045         window.withdraw()
   1046 

/usr/lib/python3.6/tkinter/__init__.py in __init__(self, screenName, baseName, className, useTk, sync, use)
   2018                 baseName = baseName + ext
   2019         interactive = 0
-> 2020         self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2021         if useTk:
   2022             self._loadtk()

TclError: couldn't connect to display ":0"
```

**Comment by MMathisLab** [comment]
and when I try to launch the GUI: 

```
%gui wx
deeplabcut.label_frames(path_config_file)

An exception has occurred, use %tb to see the full traceback.

SystemExit: Unable to access the X Display, is $DISPLAY set properly?

Unable to access the X Display, is $DISPLAY set properly?
```

**Comment by DonnieKim411** [comment]
No I could not load GUI properly within Jupyter... as far as I have researched, enabling "GUI" within Jupyter is rather difficult. 

But I wanted `DISPLAY` to be visible within docker still so that if ppl wanna plot as simple as learning loss over iterations, one can simply do so within the same jupyter notebook. I think it is a nice option to provide.

It is on my to-do-list to make GUI to be supportive within Docker setting. Not necessarily to be supportive via Jupyter, but at least one can launch Docker, and within the shell (or command line),  open ipython, and run GUI from there (and I have to do it anyways for my lab purpose...)

another question: have u guys considered writing `dlc-docker` into `docker-compose`? In docker-compose version 2.3 (and yes, it must be 2.3), one can specify `runtime` to be `nvidia` and make compatible with `nvidia-docker`. Maybe this is something I can also work on...

Cheers,

**Comment by MMathisLab** [comment]
I'm confused then why you install wxPython then? even from the command line, it does not launch from inside the container: 

```
mackenzie@6dd98ba1c6ee:/$ ipython
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut

In [2]: path_config_file = '/home/mackenzie/DEEPLABCUT/DeepLabCut/examples/Reach
   ...: ing-Mackenzie-2019-02-08/config.yaml'

In [3]: deeplabcut.label_frames(path_config_file)
An exception has occurred, use %tb to see the full traceback.

SystemExit: Unable to access the X Display, is $DISPLAY set properly?


In [4]: 

```

**Comment by MMathisLab** [comment]
this repo says they have GUI support, although I have not tested it. If you have time, maybe that is a good merge: https://github.com/eqs/DeepLabCut-Docker

**Comment by MMathisLab** [comment]
could you provide an example of this: 

"But I wanted `DISPLAY` to be visible within docker still so that if ppl wanna plot as simple as learning loss over iterations, one can simply do so within the same jupyter notebook. I think it is a nice option to provide." 

so I can test it locally on my machine before accepting the pull

**Comment by MMathisLab** [comment]
This merge makes the docker image larger, but increases usability for some users. If you wish to use display, you need to set this in the container build: ` -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ` this package now does not require DLClight=True, but there is still limited functionality of the GUIs

**Pull request merged**
